[package]

# Semantic Versioning is used: https://semver.org/
version = "0.1.0"

# Description
category = "isaaclab"
readme  = "README.md"

title = "Isaac Lab Pick-and-Place Tasks for the UR10e Robot"
author = "Marc Bischof"
maintainer = "Marc Bischof"
description="Sim-to-Real Transfer for Vision-Based Pick-and-Place"
repository = "https://github.com/booooza/IsaacLabUR10eSim2Real"
keywords = ["extension", "sim-to-real", "isaaclab", "robotics"]

[dependencies]
"isaaclab" = {}
"isaaclab_assets" = {}
"isaaclab_mimic" = {}
"isaaclab_rl" = {}
"isaaclab_tasks" = {}
# NOTE: Add additional dependencies here

[[python.module]]
name = "ur10e_sim2real"

[isaaclab_settings]
# TODO: Uncomment and list any apt dependencies here.
#       If none, leave it commented out.
# apt_deps = ["example_package"]
# TODO: Uncomment and provide path to a ros_ws
#       with rosdeps to be installed. If none,
#       leave it commented out.
# ros_ws = "path/from/extension_root/to/ros_ws"
